# Generated by Django 5.0.6 on 2024-06-18 01:29

import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.template.defaulttags.now),
        ),
    ]
