# Generated by Django 5.0.6 on 2024-06-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_category_user_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
